name: Manual CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter environment"
        required: false
        type: string

jobs:
  build:
    if: ${{ inputs.environment != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Show input
        env:
          ENVIRONMENT_INPUT: ${{ inputs.environment }}
        run: echo "Environment- $ENVIRONMENT_INPUT"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt